name: ruler_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.0+4

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  shared_preferences: ^2.1.0
  provider: ^6.0.5
  sqflite: ^2.2.7
  intl: ^0.19.0
  path: ^1.8.2
  url_launcher: ^6.3.0
  flutter_localizations: 
    sdk: flutter
  localization: ^2.1.0
  google_fonts: ^6.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - lib/i18n/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
        - asset: assets/fonts/roboto_bold.ttf
          weight: 700

flutter_launcher_icons:
  image_path: "assets/icons/ic_launcher.png"
  android: true 
  adaptive_icon_background: "assets/icons/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/icons/ic_launcher_foreground.png"
  adaptive_icon_monochrome: "assets/icons/ic_launcher_monochrome.png"
  min_sdk_android: 21
  ios: false